### ISSUE TITLE
Runtime Error since last update

### ISSUE THREAD

**Issue by ferhaterata** [ogrebenyuk/compilerexplorer#11]
Hi, I have been receiving the following error on the compiler explorer sidebar since the last update (6/16/20). Could you help to resolve this issue?

````
Internal Compiler Explorer error: TypeError: Cannot read property 'executorRequest' of undefined
    at /infra/.deploy/lib/base-compiler.js:765:32
    at run (/infra/.deploy/node_modules/p-queue/dist/index.js:249:147)
    at PQueue._tryToStartAnother (/infra/.deploy/node_modules/p-queue/dist/index.js:197:38)
    at /infra/.deploy/node_modules/p-queue/dist/index.js:263:18
    at new Promise (<anonymous>)
    at PQueue.add (/infra/.deploy/node_modules/p-queue/dist/index.js:244:16)
    at CompilationQueue.enqueue (/infra/.deploy/lib/compilation-queue.js:43:28)
    at CompilationEnvironment.enqueue (/infra/.deploy/lib/compilation-env.js:122:38)
    at DefaultCompiler.compile (/infra/.deploy/lib/base-compiler.js:759:25)
    at runMicrotasks (<anonymous>)
````
![image](https://user-images.githubusercontent.com/5862659/84842505-4c592800-b013-11ea-9272-ece084c0da1e.png)

Thanks,

**Comment by ogrebenyuk** [comment]
Thanks for the report! I have pushed a new version. Whenever it gets approved by JetBrains moderators, you will be able to upgrade to it.

**Comment by ferhaterata** [comment]
Thank you for your prompt response!

**Comment by ferhaterata** [comment]
It works after the update. Thanks!

![image](https://user-images.githubusercontent.com/5862659/84910191-929a9f80-b084-11ea-9385-1ae22c6bcff4.png)
