### ISSUE TITLE
Plugin not working in CLion latest version

### ISSUE THREAD

**Issue by maxcomperatore** [ogrebenyuk/compilerexplorer#26]
When I open the ide with the plugin enabled, i get this error from the plugin:

java.lang.AssertionError
	at com.compilerexplorer.project.oc.OCProjectSettingsProducer.getHostMachine(OCProjectSettingsProducer.java:85)
	at com.compilerexplorer.project.oc.OCProjectSettingsProducer.lambda$collect$1(OCProjectSettingsProducer.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at com.compilerexplorer.project.oc.OCProjectSettingsProducer.collect(OCProjectSettingsProducer.java:77)
	at com.compilerexplorer.project.oc.OCProjectSettingsProducer.collect(OCProjectSettingsProducer.java:48)
	at com.compilerexplorer.project.oc.OCProjectSettingsProducer.get(OCProjectSettingsProducer.java:42)
	at com.compilerexplorer.project.oc.OCProjectSettingsProducer.get(OCProjectSettingsProducer.java:31)
	at com.compilerexplorer.project.ProjectListener.refresh(ProjectListener.java:31)
	at com.compilerexplorer.common.component.BaseLinkedComponent.lambda$refreshNext$0(BaseLinkedComponent.java:26)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

![image-6.png](https://github.com/ogrebenyuk/compilerexplorer/assets/131000419/5838f742-0fe3-4cc7-82f1-6b9b2d64491d)

![message-1.txt](https://github.com/ogrebenyuk/compilerexplorer/files/12060186/message-1.txt)

I've tried to run local instances or virtual ones but it won't work. I check the virtual ones for compilers it says there are 2k+ but nothing just happens at all, the plugin tab just stays like in the image, not processes at all. I would like to address this because i really need this extension as I use compiler explorer a lot.

Moreover, there are no clear instructions whether to install this locally for getting local host or no. The plugin page has no information just bug fixes and irrelevant stuff. Consider addressing this.

Thanks.

**Comment by ogrebenyuk** [comment]
Please try the new version that released recently, and let me know if you are still seeing this problem.

Also, please note, that for this plugin to work well, you need a project in good standing with CLion - at the very least, CMake should finish successfully.

Regards,
Oleksandr

**Comment by maxcomperatore** [comment]
Yep, now it works well. What about implementing an option to able to change the font. Just suggestions, thanks for the awesome plugin. Saves time.

**Comment by ogrebenyuk** [comment]
I'll think about it
